export enum Routes {
  Homepage = '/',
  ProfileRoot = '/profile',
  ProfileKYC = '/profile/kyc/:tab?',
  ProfileWallet = '/profile/wallet/:tab?',
  ProfileDeposit = '/profile/wallet/deposit',
  ProfileWithdraw = '/profile/wallet/withdraw',
  Casino = '/casino',
  Games = '/games',
  GamesSlug = '/game/:id',
  InPlays = '/inplays',
  Sports = '/sports',
  LiveCasino = '/live-casino',
  ESports = '/e-sports',
  Promotions = '/promotions',
  PromotionSlug = '/promotions/:slug',
}
