export enum AuthActionTypes {
  Ready = 'AUTH.READY',
  SetTokens = 'AUTH.SET_TOKENS',
  SetState = 'AUTH.SET_STATE',
  Login = 'AUTH.LOGIN',
  Logout = 'AUTH.LOGOUT',
  Refresh = 'AUTH.REFRESH',
  SignUp = 'AUTH.SIGNUP',
  SetLogin = 'AUTH.SET_LOGIN',
  SetSignUp = 'AUTH.SET_SIGN_UP',
  SetUser = 'AUTH.SET_USER',
  SetRanks = 'AUTH.SET_RANKS',
  SelectCurrency = 'AUTH.SELECT_CURRENCY',
  SetUI = 'AUTH.SET_UI',
  RestorePassword = 'AUTH.RESTORE_PASSWORD',
}
